{
  "hash": "5e2b0615630cec0824c01955145da1a0",
  "result": {
    "engine": "knitr",
    "markdown": "# Dados de Área\n\n::: {.callout-tip}\n## Objetivos do Capítulo\nAo final deste capítulo, o estudante deverá ser capaz de:\n\n- Construir e interpretar mapas temáticos (coropléticos);\n- Calcular e interpretar medidas de autocorrelação espacial global (I de Moran);\n- Aplicar a análise de autocorrelação espacial local (LISA);\n- Utilizar o estimador de Bayes Empírico para suavização de taxas;\n- Ajustar modelos de regressão espacial (SAR, CAR e GWR).\n:::\n\nOs dados de área representam fenômenos agregados por unidades geográficas discretas, como municípios, estados, distritos censitários ou setores epidemiológicos. Neste capítulo, apresentamos as principais técnicas de análise para esse tipo de dado, com aplicações práticas em saúde pública.\n\n# 👉 Aplicações da Estatística Espacial \n\n## **Aplicação I:** Mapa Temático Mundial da Expectativa de Vida entre os Países\n\n#### O mapa temático tem como principal objetivo visualizar e analisar a distribuição espacial de um fenômeno específico.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tmap)\ndata(World)\ntmap_style(\"classic\")\n# Desenhando um rápido mapa temático mundial para esperança de vida.\nqtm(World, fill = \"life_exp\")\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## **Aplicação II:** Análise exploratória espacial da incidência de dengue no estado do Rio de Janeiro\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# LER A PLANILHA\n# ============================================================================\nlibrary(readxl)\nlibrary(dplyr)\n\ndengue <- read_excel(\"dados/dengue/dengue2025.xlsx\") |>\n    mutate(code_muni  = as.character(code_muni),\n           casos  = as.numeric(casos),\n           pop2022 = as.numeric(pop2022), \n           incidencia = round(casos / pop2022 * 100000, 1))\n\nhead(dengue)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"code_muni\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"municipio\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"pop2022\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"casos\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"incidencia\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3300100\",\"2\":\"Angra dos Reis\",\"3\":\"169948\",\"4\":\"1361\",\"5\":\"800.8\"},{\"1\":\"3300159\",\"2\":\"Aperibé\",\"3\":\"11174\",\"4\":\"88\",\"5\":\"787.5\"},{\"1\":\"3300209\",\"2\":\"Araruama\",\"3\":\"127254\",\"4\":\"5897\",\"5\":\"4634.0\"},{\"1\":\"3300225\",\"2\":\"Areal\",\"3\":\"13086\",\"4\":\"201\",\"5\":\"1536.0\"},{\"1\":\"3300233\",\"2\":\"Armação dos Búzios\",\"3\":\"32091\",\"4\":\"176\",\"5\":\"548.4\"},{\"1\":\"3300258\",\"2\":\"Arraial do Cabo\",\"3\":\"31561\",\"4\":\"358\",\"5\":\"1134.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n#### Lendo o Mapa {.tabset}\n\n##### Baixando via `geobr`\n\nPara acessar os dados dos limites territoriais de todos os estados brasileiros é necessário utilizar a função `read_state`.\n\n\n::: {.cell layout-align=\"center\" comments='null'}\n\n```{.r .cell-code}\n# ============================================================================\n# BAIXAR MALHA MUNICIPAL DO RJ\n# ============================================================================\nlibrary(geobr)\n\n# Baixar a malha municipal do estado do Rio de Janeiro\n# code_muni = 33 (código do estado do RJ)\n\nmapa_rj <- read_municipality(code_muni = 33, year = 2024) |>\n        mutate(code_muni = as.character(code_muni))\n```\n:::\n\n\n##### Lendo o `arquivo.shp`\n\nSupondo o `shape file` já estar em algum diretório.\n\n\n::: {.cell layout-align=\"center\" comments='null'}\n\n```{.r .cell-code}\nlibrary(sf)\nmapa_rj <- st_read(\"malhas/mapa_rj.shp\")\n```\n:::\n\n\nRenomeando as variáveis para ser semelhante ao objeto proveniente do `geobr`:\n\n\n::: {.cell layout-align=\"center\" comments='null'}\n\n```{.r .cell-code}\nmapa_rj <- mapa_rj %>%\n  rename(\n    code_muni   = code_mn,\n    name_muni = name_mn,\n    code_state = cod_stt,\n    abbrev_state = abbrv_s,\n    name_state   = nam_stt,\n    code_region  = cod_rgn,\n    name_region  = nam_rgn,\n    geom         = geometry\n  )\n```\n:::\n\n\n#### Primeiro, vamos fazer um gráfico apenas com as geometrias.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n# Visualizar rapidamente o mapa\nggplot(mapa_rj) + \n  geom_sf()\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# Left Join mapa_rj + planilha casos dengue\n# ============================================================================\nmapa_rj <- mapa_rj |>\n  mutate(code_muni = as.character(code_muni)) |>\n  left_join(dengue, by = \"code_muni\") |> \n  select(code_muni, municipio, pop2022, casos, incidencia)  \n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# Mapa Temático com as incidências de dengue por município de forma contínua\n# ============================================================================\nlibrary(ggplot2)\n\nggplot() +\n  geom_sf(data = mapa_rj, aes(fill = incidencia), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(option = \"plasma\", \n                       name = \"Incidência\\n(por 100.000 hab)\",\n                       direction = -1) +  # direction = -1 inverte a escala\n  theme_minimal() +\n  labs(title = \"Incidência de Casos nos Municípios do RJ - 2025\",\n       subtitle = \"Escala Contínua\",\n       caption = \"Fonte: Dados Simulados\") +\n  theme(legend.position = \"right\",\n        plot.title = element_text(hjust = 0.5, face = \"bold\"),\n        plot.subtitle = element_text(hjust = 0.5),\n        axis.text = element_blank(),\n        axis.title = element_blank())     \n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Sumário estatístico da incidência de dengue por município\nsummary(mapa_rj$incidencia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    51.7   723.5  1791.9  2375.7  3779.5  7458.7\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# Mapa Temático com as incidências de dengue por município de forma categórica\n# ============================================================================\n# Criar categorias usando 5 classes com método quantil\nlibrary(viridis)\n\nmap_data <- mapa_rj %>%\n  mutate(\n    incidencia_cat = cut(incidencia,\n                         breaks = c(0, 51.7, 723.5, 1791.9, 2375.7, 3779.5, 7458.7, Inf),\n                         labels = c(\"Mín - 51.7\", \n                                   \"51.7 - 723.5\", \n                                   \"723.5 - 1791.9\", \n                                   \"1791.9 - 2375.7\", \n                                   \"2375.7 - 3779.5\", \n                                   \"3779.5 - 7458.7\",\n                                   \"> 7458.7\"),\n                         include.lowest = TRUE,\n                         right = FALSE)\n  )\n\nggplot() +\n  geom_sf(data = map_data, aes(fill = incidencia_cat), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = viridis(7, option = \"plasma\", direction = -1),\n                    name = \"Incidência\\n(por 100.000 hab)\",\n                    na.translate = FALSE) +\n  theme_minimal() +\n  labs(title = \"Incidência de Casos nos Municípios do RJ\",\n       subtitle = \"Classificação por Quantis\",\n       caption = \"Fonte: Dados Simulados\") +\n  theme(legend.position = \"right\",\n        plot.title = element_text(hjust = 0.5, face = \"bold\"),\n        plot.subtitle = element_text(hjust = 0.5),\n        axis.text = element_blank(),\n        axis.title = element_blank())  \n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# Mapa Temático com as incidências de dengue por município de forma categórica\n# ============================================================================\nlibrary(classInt)\n\n# Calcular breaks Jenks\njenks_breaks <- classIntervals(mapa_rj$incidencia, n = 7, style = \"jenks\")$brks\n\n# Criar labels com os intervalos (formato igual ao da imagem, mas com os valores)\njenks_labels <- c(\n  paste0(round(jenks_breaks[1], 1), \" - \", round(jenks_breaks[2], 1)),\n  paste0(round(jenks_breaks[2], 1), \" - \", round(jenks_breaks[3], 1)),\n  paste0(round(jenks_breaks[3], 1), \" - \", round(jenks_breaks[4], 1)),\n  paste0(round(jenks_breaks[4], 1), \" - \", round(jenks_breaks[5], 1)),\n  paste0(round(jenks_breaks[5], 1), \" - \", round(jenks_breaks[6], 1)),\n  paste0(round(jenks_breaks[6], 1), \" - \", round(jenks_breaks[7], 1)),\n  paste0(\"> \", round(jenks_breaks[7], 1))\n)\n\n# Criar a variável categórica\nmapa <- mapa_rj %>%\n  mutate(\n    incidencia_cat = cut(incidencia,\n                         breaks = jenks_breaks,\n                         labels = jenks_labels,\n                         include.lowest = TRUE,\n                         right = FALSE)\n  )\n\n# Plotar o mapa\nggplot() +\n  geom_sf(data = mapa, aes(fill = incidencia_cat), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = viridis(7, option = \"plasma\", direction = -1),\n                    name = \"Incidência\\n(por 100.000 hab)\",\n                    na.translate = FALSE) +\n  theme_minimal() +\n  labs(title = \"Incidência de Casos nos Municípios do RJ\",\n       subtitle = \"Classificação por Quebras Naturais (Jenks)\",\n       caption = \"Fonte: SINAN\") +\n  theme(legend.position = \"right\",\n        plot.title = element_text(hjust = 0.5, face = \"bold\"),\n        plot.subtitle = element_text(hjust = 0.5),\n        axis.text = element_blank(),\n        axis.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n#### Matriz de Vizinhança\n\nA matriz de vizinhança é um instrumento fundamental da Estatística Espacial utilizado para representar formalmente quais áreas são consideradas vizinhas entre si. Em termos simples, ela transforma o mapa em uma estrutura matemática que indica quem é vizinho de quem.\n\nImagine os municípios de um estado. No mapa, visualmente conseguimos perceber quais compartilham fronteiras. A matriz de vizinhança traduz essa informação em números: se dois municípios são vizinhos, atribuímos valor 1; se não são, atribuímos 0. O resultado é uma tabela quadrada (n × n), onde n é o número de municípios analisados.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](figuras/vizinhanca.png){fig-align='center' width=55%}\n:::\n:::\n\n\n#### **Exemplo Simplificado de Matriz de Vizinhança**\n\n**Municípios analisados:**  \n  Rio de Janeiro, Niterói, São Gonçalo, Duque de Caxias, Nova Iguaçu  \n\n**Critério:** Contiguidade do tipo *Rainha*  \n  (considera vizinhos os municípios que compartilham qualquer ponto de fronteira)\n\n\n|            | Rio | Niterói | S. Gonçalo | D. Caxias | N. Iguaçu |\n  |:-----------|:---:|:-------:|:----------:|:---------:|:---------:|\n  | **Rio**        |  0  |    1    |     1      |     1     |     1     |\n  | **Niterói**    |  1  |    0    |     1      |     0     |     0     |\n  | **S. Gonçalo** |  1  |    1    |     0      |     0     |     0     |\n  | **D. Caxias**  |  1  |    0    |     0      |     0     |     1     |\n  | **N. Iguaçu**  |  1  |    0    |     0      |     1     |     0     |\n  \n  ---\n  \nNotas:\n  \n- **1** = municípios são vizinhos (compartilham fronteira)  \n- **0** = municípios não são vizinhos  \nA **diagonal principal é zero**, pois um município não é vizinho de si mesmo.\n\nEssa matriz é essencial porque muitos fenômenos da gestão pública apresentam dependência espacial. Ou seja, o que acontece em um município pode influenciar municípios vizinhos. Exemplos incluem:\n  \n- Propagação de doenças (como dengue);\n- Dinâmica do desemprego;\n- Criminalidade;\n- Poluição ambiental;\n- Expansão urbana.\n\nSem a matriz de vizinhança, os métodos utilizados na estatísticos estatística tratariam cada município como independente. Com ela, conseguimos incorporar a ideia de que “o território importa”.\n\nExistem diferentes critérios para definir vizinhança:\n  \n- Contiguidade (compartilham fronteira);\n\n- Distância (municípios dentro de um raio específico);\n\n- k-vizinhos mais próximos (cada área tem um número fixo de vizinhos).\n\nA escolha do critério depende do problema de política pública analisado. Para doenças transmissíveis, por exemplo, a contiguidade territorial pode ser adequada. Já para fluxos econômicos, a distância ou conectividade pode fazer mais sentido.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# MATRIZ DE VIZINHANÇA DOS MUNICÍPIOS DO RIO DE JANEIRO\n# ============================================================================\n\nlibrary(spdep)\n# ============================================================================\n# 1. CRIAR A MATRIZ DE VIZINHANÇA\n# ============================================================================\n\n# Converter para objeto sp (formato exigido por alguns pacotes)\n# Mas o spdep também aceita sf diretamente\nrj_sp <- as(mapa_rj, \"Spatial\")\n\n# Criar lista de vizinhos baseada em contiguidade (critério \"rainha\" - queen)\n# queen = TRUE considera vizinhos que compartilham qualquer ponto da fronteira\nvizinhos_rainha <- poly2nb(mapa_rj, queen = TRUE)\n\n# Criar lista de vizinhos baseada em contiguidade (critério \"torre\" - rook)\n# queen = FALSE considera apenas vizinhos com fronteira lateral\nvizinhos_torre <- poly2nb(mapa_rj, queen = FALSE)\n\n# Verificar o resultado\nsummary(vizinhos_rainha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Neighbour list object:\n#> Number of regions: 92 \n#> Number of nonzero links: 438 \n#> Percentage nonzero weights: 5.174858 \n#> Average number of links: 4.76087 \n#> Link number distribution:\n#> \n#>  1  2  3  4  5  6  7  8  9 \n#>  3  7 18 16 15 14 11  5  3 \n#> 3 least connected regions:\n#> 5 34 53 with 1 link\n#> 3 most connected regions:\n#> 49 50 55 with 9 links\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(vizinhos_torre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Neighbour list object:\n#> Number of regions: 92 \n#> Number of nonzero links: 402 \n#> Percentage nonzero weights: 4.749527 \n#> Average number of links: 4.369565 \n#> Link number distribution:\n#> \n#>  1  2  3  4  5  6  7  8  9 \n#>  3 10 22 17 14 15  5  4  2 \n#> 3 least connected regions:\n#> 5 34 53 with 1 link\n#> 2 most connected regions:\n#> 49 55 with 9 links\n```\n\n\n:::\n:::\n\n\n| Item do Output                   | O que representa |\n  |----------------------------------|------------------|\n  | Number of regions               | Número total de unidades territoriais analisadas (ex.: municípios). |\n  | Number of nonzero links         | Total de conexões de vizinhança existentes entre as áreas. |\n  | Percentage nonzero weights      | Percentual de conexões existentes em relação ao total possível de conexões. |\n  | Average number of links         | Número médio de vizinhos por unidade territorial. |\n  | Link number distribution        | Distribuição do número de vizinhos entre as áreas analisadas. |\n  | Least connected regions         | Unidades territoriais com menor número de vizinhos. |\n  | Most connected regions          | Unidades territoriais com maior número de vizinhos. |\n  \n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# 2. CONVERTER PARA MATRIZ DE VIZINHANÇA (FORMATO TABELA)\n# ============================================================================\n\n# Converter lista de vizinhos para matriz binária\nmatriz_vizinhos_rainha <- nb2mat(vizinhos_rainha, style = \"B\", zero.policy = TRUE)\nmatriz_vizinhos_torre <- nb2mat(vizinhos_torre, style = \"B\", zero.policy = TRUE)\n\n# Visualizar as primeiras linhas e colunas da matriz\nprint(matriz_vizinhos_rainha[1:10, 1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]\n#> 1     0    0    0    0    0    0    0    0    0     0\n#> 2     0    0    0    0    0    0    0    0    0     0\n#> 3     0    0    0    0    0    1    0    0    0     0\n#> 4     0    0    0    0    0    0    0    0    0     0\n#> 5     0    0    0    0    0    0    0    0    0     0\n#> 6     0    0    1    0    0    0    0    0    0     0\n#> 7     0    0    0    0    0    0    0    1    0     0\n#> 8     0    0    0    0    0    0    1    0    0     0\n#> 9     0    0    0    0    0    0    0    0    0     0\n#> 10    0    0    0    0    0    0    0    0    0     0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verificar dimensões (deve ser 92x92, pois são 92 municípios)\ndim(matriz_vizinhos_rainha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 92 92\n```\n\n\n:::\n:::\n\n\n#### Verificando a malha de conectividade da vizinhança da cidade do Rio de Janeiro/RJ\n\n* Iremos precisar da coordenadas dos centróides para montar a malha de conectividade.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sp)\nmapa_rj.sp <- as(mapa_rj, 'Spatial') # convertendo em formato sp\ncoord <- coordinates(mapa_rj.sp) # coordenadas dos centroides dos poligonos do RJ\nclass(mapa_rj.sp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"SpatialPolygonsDataFrame\"\n#> attr(,\"package\")\n#> [1] \"sp\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nviz.sf <- as(nb2lines(vizinhos_rainha, coords = coord), 'sf')\nviz.sf <- st_set_crs(viz.sf, st_crs(mapa_rj))\n```\n:::\n\n\n::: box-dica2\n- `st_set_crs()` define o sistema de referência de coordenadas (CRS) do objeto `viz.sf`.\n\n- Ele está copiando o CRS do objeto `setor.sf`, garantindo que os dois objetos estejam no mesmo sistema de coordenadas.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plotando o grafo de conectividade por contiguidade\nmapa.viz <- ggplot(mapa_rj) + \n  geom_sf(fill = 'lightpink', color = 'white') +\n  geom_sf(data = viz.sf) +\n  theme_minimal() +\n  ggtitle(\"Vizinhança por conectividade (vizinhos_rainha)\") +\n  ylab(\"Latitude\") +\n  xlab(\"Longitude\")\nmapa.viz\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n  \n#### Autocorrelação espacial\n\n🔎 **Moran Global**\n\nO Moran Global é uma medida sintética que avalia se existe autocorrelação espacial em todo o território analisado. Em outras palavras, ele indica se municípios vizinhos tendem a apresentar valores semelhantes para determinado indicador, como renda, taxa de mortalidade ou incidência de dengue. Quando o índice é positivo e estatisticamente significativo, significa que áreas próximas apresentam padrões semelhantes (alto com alto, baixo com baixo), revelando a existência de agrupamentos espaciais. Quando é próximo de zero, sugere ausência de padrão espacial. \n\nO Moran Global é importante porque permite verificar se o fenômeno analisado possui organização territorial, indicando a necessidade de políticas regionais integradas em vez de intervenções isoladas.\n\n$$I = \\frac{ \\sum_{i=1}^{n} \\sum_{j=1}^{n} w_{ij} (y_i - \\bar{y})(y_j - \\bar{y}) }{ \\sum_{i=1}^{n} (y_i - \\bar{y})^2 }$$\n  \n::: box-dica4\n\n* $I > 0$: valores similares estão próximos (agrupamento positivo).\n\n* $I < 0$: valores diferentes estão próximos (dispersão).\n\n* $I \\approx 0$: padrão aleatório.\n\n:::\n  \nSabendo que:\n  \n- \\( I \\): valor do índice de Moran global.\n- \\( n \\): número total de unidades espaciais (regiões).\n- \\( y_i \\): valor da variável de interesse na região \\( i \\).\n- \\( \\bar{y} \\): média dos valores de \\( y \\) em todas as regiões.\n- \\( w_{ij} \\): elemento da matriz de vizinhança que representa a relação espacial entre as regiões \\( i \\) e \\( j \\).\n- \\( w_{ij} = 1 \\) se \\( i \\) e \\( j \\) são vizinhos, 0 caso contrário (ou ponderado).\n- O numerador mede a covariância espacial ponderada, e o denominador é a variância total de \\( y \\).\n\n#### Autocorrelação espacial dos casos de dengue nos municípios/RJ\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npesos.viz <- nb2listw(vizinhos_torre)\nmoran.test(mapa$casos, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  mapa$casos  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = 2.8562, p-value = 0.002144\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>       0.032331341      -0.010989011       0.000230046\n```\n\n\n:::\n:::\n\n\nO resultado do teste de Moran’s I indicou autocorrelação espacial positiva estatisticamente significativa $(I = 0,0324; Z = 2,88; p = 0,0019)$. Como o valor observado é superior ao valor esperado $(E[I] = −0,0109)$ e o p-valor é inferior a $0,05$, rejeita-se a hipótese nula de ausência de dependência espacial. Isso sugere que municípios vizinhos tendem a apresentar valores semelhantes da variável analisada, caracterizando um padrão de agrupamento espacial. Contudo, apesar de estatisticamente significativo, o valor do índice é de baixa magnitude, indicando que a intensidade da autocorrelação espacial é relativamente fraca.\n\n#### Autocorrelação espacial para incidências de dengue nos municípios/RJ\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoran.test(mapa$incidencia, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  mapa$incidencia  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = -0.57317, p-value = 0.7167\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>      -0.053004448      -0.010989011       0.005373449\n```\n\n\n:::\n:::\n\n\nO teste de Moran indicou ausência de autocorrelação espacial significativa na incidência analisada $(I = −0,055; p-valor = 0,71)$. Como o valor do índice é próximo de zero e o $p-valor$ é superior a $0,05$, não há evidências para rejeitar a hipótese de aleatoriedade espacial. Assim, os dados não apresentam padrão de agrupamento ou dispersão no espaço, sugerindo que a variação observada não está associada à localização geográfica das áreas estudadas.\n\n📍 **Moran Local (LISA)**\n\nO Moran Local, também conhecido como LISA (*Local Indicators of Spatial Association*), aprofunda a análise ao avaliar a autocorrelação espacial em cada unidade territorial individualmente. Diferentemente do Moran Global, que fornece um único valor para todo o estado ou país, o Moran Local identifica onde exatamente estão os agrupamentos espaciais e possíveis áreas atípicas. Ele permite classificar cada município como parte de um cluster de valores altos, um cluster de valores baixos ou como um ponto fora do padrão em relação aos seus vizinhos. Essa análise é fundamental para identificar territórios prioritários e direcionar recursos de forma mais estratégica.\n\nAvalia a autocorrelação espacial **local**, permitindo identificar regiões com agrupamentos (clusters) ou comportamentos atípicos.\n\n$$I^{(i)} = \\frac{n}{\\sum_{j=1}^{n} (z_j - \\bar{z})^2} \\sum_{j=1}^{n} w_{ij} (z_i - \\bar{z})(z_j - \\bar{z})$$\n  \nSabendo que:\n  \n- \\( I^{(i)} \\): índice de Moran local para a região \\( i \\).\n- \\( n \\): número total de regiões.\n- \\( z_i \\): valor padronizado (ou original, dependendo da convenção) da variável na região \\( i \\).\n- \\( \\bar{z} \\): média da variável \\( z \\).\n- \\( w_{ij} \\): peso espacial entre as regiões \\( i \\) e \\( j \\).\n- A soma considera a influência dos vizinhos \\( j \\) sobre o ponto \\( i \\), ponderada pela matriz de vizinhança.\n\n#### Mapeando os polígonos que tiveram os p-valores mais significativos no Moran Local para os casos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmapa$pval <- localmoran(mapa$casos, pesos.viz)[,5]\n\nlibrary(tmap)\n\ntmap_mode(\"plot\")  # modo estático\n\ntm_shape(mapa) + \n  tm_polygons(\n    col = \"pval\",\n    title = \"p-valores\",\n    breaks = c(0, 0.01, 0.05, 0.10, 1),\n    style = \"fixed\",\n    palette = \"-Red\"\n  )\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n#### Moran Local dos casos de dengue no Rio de Janeiro/RJ\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresI <- localmoran.sad(lm(mapa$casos ~ 1), 1:length(vizinhos_torre), vizinhos_torre, style = \"W\")\nsummary(resI)[1:10,]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Local Morans I\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Stand. dev. (N)\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr. (N)\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Saddlepoint\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr. (Sad)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Expectation\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Variance\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Skewness\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Kurtosis\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Minimum\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Maximum\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"omega\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sad.r\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sad.u\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.021050792\",\"2\":\"0.056717658\",\"3\":\"0.9547701\",\"4\":\"0.07810819\",\"5\":\"0.9377420\",\"6\":\"-0.01098901\",\"7\":\"0.3191120\",\"8\":\"-0.10931976\",\"9\":\"8.273262\",\"10\":\"-26.47916\",\"11\":\"25.47916\",\"12\":\"1.079775e-03\",\"13\":\"0.05612152\",\"14\":\"0.056190813\",\"_rn_\":\"1 1\"},{\"1\":\"0.026138759\",\"2\":\"0.065724502\",\"3\":\"0.9475972\",\"4\":\"0.09345286\",\"5\":\"0.9255438\",\"6\":\"-0.01098901\",\"7\":\"0.3191120\",\"8\":\"-0.10931976\",\"9\":\"8.273262\",\"10\":\"-26.47916\",\"11\":\"25.47916\",\"12\":\"1.250586e-03\",\"13\":\"0.06502785\",\"14\":\"0.065148156\",\"_rn_\":\"2 2\"},{\"1\":\"0.005983561\",\"2\":\"0.043216817\",\"3\":\"0.9655287\",\"4\":\"0.04683929\",\"5\":\"0.9626413\",\"6\":\"-0.01098901\",\"7\":\"0.1542374\",\"8\":\"-0.15720340\",\"9\":\"8.281504\",\"10\":\"-18.55778\",\"11\":\"17.55778\",\"12\":\"1.185290e-03\",\"13\":\"0.04278043\",\"14\":\"0.042787857\",\"_rn_\":\"3 3\"},{\"1\":\"0.022003280\",\"2\":\"0.058403776\",\"3\":\"0.9534270\",\"4\":\"0.08098279\",\"5\":\"0.9354556\",\"6\":\"-0.01098901\",\"7\":\"0.3191120\",\"8\":\"-0.10931976\",\"9\":\"8.273262\",\"10\":\"-26.47916\",\"11\":\"25.47916\",\"12\":\"1.111777e-03\",\"13\":\"0.05778911\",\"14\":\"0.057866618\",\"_rn_\":\"4 4\"},{\"1\":\"0.021013026\",\"2\":\"0.032349886\",\"3\":\"0.9741930\",\"4\":\"0.04454608\",\"5\":\"0.9644691\",\"6\":\"-0.01098901\",\"7\":\"0.9786102\",\"8\":\"-0.06243625\",\"9\":\"8.268062\",\"10\":\"-46.00000\",\"11\":\"45.00000\",\"12\":\"3.516478e-04\",\"13\":\"0.03200332\",\"14\":\"0.032016170\",\"_rn_\":\"5 5\"},{\"1\":\"0.015317263\",\"2\":\"0.046568022\",\"3\":\"0.9628575\",\"4\":\"0.06078805\",\"5\":\"0.9515280\",\"6\":\"-0.01098901\",\"7\":\"0.3191120\",\"8\":\"-0.10931976\",\"9\":\"8.273262\",\"10\":\"-26.47916\",\"11\":\"25.47916\",\"12\":\"8.869148e-04\",\"13\":\"0.04608115\",\"14\":\"0.046112391\",\"_rn_\":\"6 6\"},{\"1\":\"0.015704683\",\"2\":\"0.073841006\",\"3\":\"0.9411369\",\"4\":\"0.09683401\",\"5\":\"0.9228582\",\"6\":\"-0.01098901\",\"7\":\"0.1306839\",\"8\":\"-0.17076788\",\"9\":\"8.284377\",\"10\":\"-17.12077\",\"11\":\"16.12077\",\"12\":\"2.199319e-03\",\"13\":\"0.07310655\",\"14\":\"0.073233475\",\"_rn_\":\"7 7\"},{\"1\":\"0.003608601\",\"2\":\"0.040380411\",\"3\":\"0.9677898\",\"4\":\"0.03965131\",\"5\":\"0.9683711\",\"6\":\"-0.01098901\",\"7\":\"0.1306839\",\"8\":\"-0.17076788\",\"9\":\"8.284377\",\"10\":\"-17.12077\",\"11\":\"16.12077\",\"12\":\"1.203499e-03\",\"13\":\"0.03997558\",\"14\":\"0.039975064\",\"_rn_\":\"8 8\"},{\"1\":\"-0.012493431\",\"2\":\"-0.002162481\",\"3\":\"1.0017254\",\"4\":\"-0.01897344\",\"5\":\"0.9848623\",\"6\":\"-0.01098901\",\"7\":\"0.4839865\",\"8\":\"-0.08877480\",\"9\":\"8.270634\",\"10\":\"-32.49609\",\"11\":\"31.49609\",\"12\":\"-3.342014e-05\",\"13\":\"-0.00213903\",\"14\":\"-0.002139107\",\"_rn_\":\"9 9\"},{\"1\":\"0.025821000\",\"2\":\"0.075664126\",\"3\":\"0.9396863\",\"4\":\"0.10737515\",\"5\":\"0.9144914\",\"6\":\"-0.01098901\",\"7\":\"0.2366747\",\"8\":\"-0.12692798\",\"9\":\"8.275948\",\"10\":\"-22.87186\",\"11\":\"21.87186\",\"12\":\"1.671625e-03\",\"13\":\"0.07486838\",\"14\":\"0.075050814\",\"_rn_\":\"10 10\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: box-dica2 \n\n- A função `localmoran.sad()` calcula o Moran Local `(Iᵢ)` e algumas outras estatísticas associadas para cada polígono (setor).\n\n- `lm(setor.sf$tx ~ 1)`:  cria um modelo linear sem preditores (apenas o intercepto), ou seja, considera a variável `casos` como resposta a ser analisada.\n\n- `1:length(viz)`: identifica o índice de cada área/setor.\n\n- `viz`: é a estrutura de vizinhança (do tipo `nb`), que define quem é vizinho de quem.\n\n- `style = \"W\"`: define o estilo de normalização dos pesos espaciais (padronização row-standardized).\n\n:::\n\n- A está mostrando:\n\n  * `Local Morans I`:\tValor do I de Moran local `(Iᵢ)`, indicando se o valor do setor e seus vizinhos são semelhantes (positivo) ou diferentes (negativo).\n  \n  * `Stand. dev. (N)`:\tDesvio padrão padronizado da estatística de Moran local.\n  \n  * `Pr. (N)`:\tp-valor do teste de significância para o valor de `Iᵢ` (baseado na dist. normal).\n  \n  * `Saddlepoint`:\tValor do I de Moran local corrigido.\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmapa$MoranLocal <- summary(resI)[,1] \n\nlibrary(scales)\n\nggplot(mapa) + \n  geom_sf(aes(fill = MoranLocal), color = 'black') +\n  scale_fill_gradientn(colours=c(\"blue\", \"white\", \"red\"), \n                       values=rescale(c(min(mapa$MoranLocal), 0,   max(mapa$MoranLocal))), guide=\"colorbar\") + \n  ggtitle(\"Moran local\") + \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nNeste mapa, podemos observar:\n\n- Valores altos de Local Morans I com p-valor pequeno indicam clusters estatisticamente significativos:\n\n  * Positivo + significativo $\\rightarrow$ cluster alto-alto ou baixo-baixo.\n\n  * Negativo + significativo $\\rightarrow$ outlier (ex: um valor alto cercado por baixos, ou o contrário).\n  \n🗺 **LISA Map**\n\nO LISA Map é um mapa temático que representa graficamente os resultados do Índice de Moran Local, ele identifica:\n  \n- Clustering local (agrupamento de valores semelhantes)\n\n- Outliers espaciais (valores discrepantes em relação aos vizinhos)\n\n- Regiões não significativas (sem padrão espacial detectável)\n\n\n| Tipo de Associação        | Descrição                                                | Interpretação Espacial                                                |\n  | ------------------------- | -------------------------------------------------------- | --------------------------------------------------------------------- |\n  | 🔴 **Alto-Alto (High-High)** | Valor alto cercado por vizinhos também com valores altos | Indica **cluster de altas magnitudes**, também chamado de **hotspot** |\n  | 🔵 **Baixo-Baixo (Low-Low)** | Valor baixo cercado por vizinhos com valores baixos      | Indica **cluster de baixas magnitudes**, ou **coldspot**              |\n  | 🟠 **Alto-Baixo (High-Low)** | Valor alto cercado por valores baixos                    | Indica um **outlier espacial positivo**                               |\n  | 🟡 **Baixo-Alto (Low-High)** | Valor baixo cercado por valores altos                    | Indica um **outlier espacial negativo**                               |\n  | ⚪ **Não significativo**     | Sem associação espacial relevante                        | O valor na região não apresenta padrão espacial detectável            |\n  \n  \n* Os valores do Moran Local são testados por permutação para verificar se o padrão observado é estatisticamente significativo ou poderia ocorrer por acaso.\n\n* Apenas as regiões significativas (p-valor < 0.05) costumam ser coloridas nos mapas.\n\nEsse mapa abaixo pertence ao artigo [\"Are regions equal in adversity? A spatial analysis of the spread and dynamics of COVID-19 in Europe\", de Amdaoud, Arcuri e Levratto (2021)](https://www.researchgate.net/publication/349729379_Are_regions_equal_in_adversity_A_spatial_analysis_of_the_spread_and_dynamics_of_COVID-19_in_Europe). O artigo realiza uma análise espacial detalhada da mortalidade por COVID-19 em 125 regiões europeias durante a primeira onda da pandemia (março a maio de 2020). \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](figuras/lisa_map_covid.png){fig-align='center' width=80%}\n:::\n:::\n\n\nUtilizando o índice de Moran Local (LISA), o estudo identifica padrões de autocorrelação espacial na mortalidade por COVID-19 entre as regiões europeias durante a primeira onda da pandemia. O resultado evidencia clusters espaciais significativos, com destaque para regiões High-High (altas taxas de mortalidade cercadas por outras com altas taxas), como o norte da Itália, Madrid e a região da Alsácia, na França. Ao mesmo tempo, regiões Low-Low, como o sul da Itália, Dinamarca e partes da Alemanha Oriental, apresentaram baixa mortalidade em vizinhança igualmente baixa. Esses padrões persistentes ao longo do tempo indicam que a disseminação da pandemia seguiu lógicas regionais, reforçando a importância de políticas públicas que considerem as desigualdades territoriais na resposta à crise sanitária.\n\n**Autocorrelação espacial dos casos confirmados de covid-19 em municípios sede de regionais\nde saúde e vizinhos, segundo a análise do Índice Local de Moran (LISA) Univariado. Paraná, Brasil,\nmarço de 2020 a janeiro de 2021.**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](figuras/moran_local3_covid.png){fig-align='center' width=90%}\n:::\n:::\n\n\n[COVRE, Eduardo Rocha et al. Correlação espacial da covid-19 com leitos de unidades de terapia intensiva no Paraná. Revista de Saúde Pública, v. 56, p. 14, 2022.](https://www.scielo.br/j/rsp/a/NDB7dYnVxgbtWPFskqxMgKR/?lang=pt)\n\nNa figura acima, observamos que o valor do Índice de Moran Global foi de $0,404$, com $p-valor < 0,001$, indicando uma autocorrelação espacial positiva moderada e estatisticamente significativa. Isso significa que a distribuição dos casos não ocorreu de forma aleatória no território paranaense – pelo contrário, municípios com taxas semelhantes de COVID-19 tenderam a se agrupar no espaço.\n\nObservando o mapa LISA (Indicadores Locais de Associação Espacial), podemos identificar diferentes padrões regionais. As áreas em vermelho (Alto-Alto) representam municípios com altas taxas da doença cercados por vizinhos igualmente afetados, formando verdadeiros \"clusters de transmissão\" que exigiam intervenções coordenadas e prioritárias. Por outro lado, as áreas em azul escuro (Baixo-Baixo) mostram regiões onde tanto o município quanto seus vizinhos mantiveram baixas taxas, sugerindo que estratégias de controle podem ter sido mais eficazes nessas localidades.\n\nAs áreas em rosa (Alto-Baixo) e azul claro (Baixo-Alto) revelam situações de transição ou exceção, onde um município destoa do padrão de seus vizinhos. Estes são pontos de atenção para a vigilância em saúde, pois podem indicar locais onde a doença se comporta de forma diferente da região de entorno. Já as áreas em cinza (Não significante) não apresentaram padrão espacial definido, podendo refletir maior heterogeneidade local ou dinâmicas de transmissão mais complexas.\n\n\n#### **LISA Map dos casos de dengue na cidade do Rio de Janeiro/RJ**\n\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(spdep)\n\n#  Convertendo uma estrutura de vizinhança (objeto nb) em uma matriz de pesos espaciais padronizada\nw <- nb2listw(vizinhos_torre, style = \"W\")\n\n# Matriz de pesos espaciais padronizada (row-standardized)\nresI <- localmoran(mapa$casos, nb2listw(vizinhos_torre, style = \"W\"))\n\n# Armazena estatísticas no objeto espacial\nmapa$Ii       <- resI[,1]   # valor de Moran Local\nmapa$pvalue   <- resI[,5]   # p-valor\n\n# Valor padronizado da variável tx\nmapa$z_casos <- scale(mapa$casos)[, 1]\n\n# Média dos vizinhos (lagged value)\nlag_casos <- lag.listw(w, mapa$z_casos)\n\n# Classificação dos tipos de associação local dos clusters\nmapa$cluster_type <- \"Não significativo\"\n\nmapa$cluster_type[mapa$pvalue <= 0.05 & mapa$z_casos > 0 & lag_casos > 0] <- \"Alto-Alto\"\nmapa$cluster_type[mapa$pvalue <= 0.05 & mapa$z_casos < 0 & lag_casos < 0] <- \"Baixo-Baixo\"\nmapa$cluster_type[mapa$pvalue <= 0.05 & mapa$z_casos > 0 & lag_casos < 0] <- \"Alto-Baixo\"\nmapa$cluster_type[mapa$pvalue <= 0.05 & mapa$z_casos < 0 & lag_casos > 0] <- \"Baixo-Alto\"\n```\n:::\n\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tmap)\n\n# Modo estático (ideal para relatórios impressos ou PDF)\ntmap_mode(\"plot\")\n\n# Tema visual limpo com fundo branco\ntmap_style(\"white\")\n\n# Geração do mapa LISA\ntm_shape(mapa) +\n  tm_fill(\n    col = \"cluster_type\",\n    palette = c(\n      \"Alto-Alto\"         = \"#E60000\",  # vermelho forte\n      \"Baixo-Baixo\"       = \"#0033CC\",  # azul escuro\n      \"Baixo-Alto\"        = \"#9999FF\",  # azul claro\n      \"Alto-Baixo\"        = \"#FF9999\",  # rosa claro\n      \"Não significativo\" = \"#FFFFFF\"   # branco\n    ),\n    title = \"Cluster Local (LISA)\",\n    legend.is.portrait = TRUE\n  ) +\n  tm_borders(col = \"gray40\", lwd = 0.4) +\n  tm_layout(\n    main.title = \"Mapa LISA - Clusters Locais dos Casos\",\n    main.title.size = 1.2,\n    legend.outside = TRUE,\n    frame = FALSE,\n    bg.color = \"white\"\n  )\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n🎯 Diferença resumida\n\n* Moran Global → Existe padrão espacial no estado como um todo ?\n\n* Moran Local (LISA) → Onde estão esses padrões ?\n\n* LISA Map → Visualização espacial desses agrupamentos.\n\n::: box-dica2\n\n🗺️ Resumindo\n\n- **Moran Global** indica se há padrão geral de autocorrelação espacial (positivo, negativo ou aleatório).\n\n- **Moran Local** revela **onde** esses padrões ocorrem: clusters de alto/alto (*hotspots*), baixo/baixo (*coldspots*), alto/baixo (*outliers*), etc.\n\n:::\n\n\n#### **# Bayesiano Empírico: Global e Local**\n\n##### A ideia central\n\nImagine que você quer estimar a taxa de uma doença em vários municípios. O problema: municípios pequenos têm taxas **instáveis** — um único caso pode triplicar a taxa de um ano para o outro. Como resolver isso?\n\nO **Bayesiano Empírico** \"suaviza\" a taxa observada de cada área, combinando-a com uma **média de referência**:\n\n$$\\hat{\\theta}_i = w_i \\cdot t_i + (1 - w_i) \\cdot \\mu$$\n\n**Leia assim:** a taxa estimada é uma média ponderada entre a taxa local ($t_i$) e uma referência ($\\mu$), controlada pelo peso $w_i$.\n\nO peso $w_i$ depende do tamanho da população:\n\n- **Município grande** $\\rightarrow$ $w_i$ próximo de 1 $\\rightarrow$ confia na taxa observada\n\n- **Município pequeno** $\\rightarrow$ $w_i$ próximo de 0 $\\rightarrow$ puxa para a média de referência\n\n\n**Bayesiano Empírico Global**\n\nA referência é a **média geral de toda a região**. Um município com poucos habitantes é \"puxado\" para essa média geral.\n\n**Exemplo:** município rural com 1 caso em 200 pessoas (taxa altíssima). O método reconhece que a população é pequena e suaviza a estimativa em direção à média do estado.\n\n\n**Bayesiano Empírico Local**\n\nA referência é a **média dos municípios vizinhos**. A ideia é que municípios próximos tendem a ter condições parecidas (clima, renda, acesso à saúde).\n\n**Exemplo:** o mesmo município rural agora é comparado com seus vizinhos imediatos, não com todo o estado. Isso respeita melhor a heterogeneidade regional.\n\n\n**Global vs. Local: qual é a diferença ?**\n\nA diferença está em **quem é a referência** ($\\mu$):\n\n| | **Global** | **Local** |\n|---|---|---|\n| **Referência** | Média de *todas* as áreas | Média dos *vizinhos* |\n| **Hipótese** | Todas as áreas se parecem | Áreas próximas se parecem |\n| **Quando usar** | Região homogênea | Quando há padrão espacial |\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# CALCULAR CASOS ESPERADOS\n# ============================================================================\n\n# Calcular a taxa global de incidência\ntaxa_global <- sum(mapa_rj$casos, na.rm = TRUE) / sum(mapa_rj$pop2022, na.rm = TRUE) * 100000\n\n# Calcular casos esperados (pop * taxa_global / 100000)\nmapa_rj <- mapa_rj |>\n    mutate(\n        casos_esperados = (pop2022 * taxa_global) / 100000,\n        risco_relativo_bruto = casos / casos_esperados,\n        incidencia_esperada = taxa_global\n    )\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# BAYES EMPÍRICO GLOBAL\n# ============================================================================\nlibrary(SpatialEpi)\n\n# Aplicar a função eBayes do pacote SpatialEpi\n# Y = casos observados\n# E = casos esperados\neb_results <- eBayes(\n    Y = mapa_rj$casos,\n    E = mapa_rj$casos_esperados\n)\n\n# Visualizar a estrutura dos resultados\nstr(eb_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> List of 5\n#>  $ RR   : num [1:92] 0.185 0.183 1.067 0.355 0.127 ...\n#>  $ RRmed: num [1:92] 0.185 0.182 1.067 0.354 0.127 ...\n#>  $ beta : Named num -0.603\n#>   ..- attr(*, \"names\")= chr \"(Intercept)\"\n#>  $ alpha: num 1.22\n#>  $ SMR  : num [1:92] 0.185 0.181 1.068 0.354 0.126 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Adicionar resultados ao mapa\nmapa_rj <- mapa_rj |>\n    mutate(\n        # Risco Relativo Bayes Empírico (posterior mean)\n        rr_ebayes = eb_results$RR,\n        \n        # Mediana posterior\n        rr_ebayes_med = eb_results$RRmed,\n        \n        # SMR (Standardized Mortality Ratio)\n        smr = eb_results$SMR,\n        \n        # Incidência suavizada\n        incidencia_suavizada = rr_ebayes * taxa_global,\n        \n        # Parâmetros do modelo\n        alpha_eb = eb_results$alpha,\n        beta_eb = eb_results$beta\n    )\n\n# Verificar resultados\nsummary(mapa_rj$rr_ebayes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#> 0.01236 0.16854 0.41324 0.54738 0.87020 1.71731\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mapa_rj$incidencia_suavizada)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>   53.65  731.53 1793.63 2375.84 3777.00 7453.77\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# BAYES EMPÍRICO LOCAL\n# ============================================================================\n\n\n# ============================================================================\n# CRIAR A MATRIZ DE VIZINHANÇA\n# ============================================================================\n\n# Criar vizinhança baseada em contiguidade (critério rainha)\nnb <- poly2nb(mapa_rj, queen = TRUE)\n\n\n# ============================================================================\n# APLICAR O ESTIMADOR LOCAL DE BAYES EMPÍRICO\n# ============================================================================\n\n# Aplicar EBlocal\n# ri = casos observados\n# ni = população (ou denominador)\n# zero.policy = TRUE para áreas sem vizinhos (usa o próprio valor)\neb_local <- EBlocal(\n    ri = mapa_rj$casos,\n    ni = mapa_rj$pop2022,\n    nb = nb,\n    zero.policy = TRUE,\n    geoda = FALSE  # Usa o algoritmo de Marshall (padrão)\n)\n\n# Visualizar a estrutura do resultado\nstr(eb_local)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> 'data.frame':\t92 obs. of  2 variables:\n#>  $ raw: num  0.00801 0.00788 0.04634 0.01536 0.00548 ...\n#>  $ est: num  0.00801 0.00789 0.04633 0.01534 0.00549 ...\n#>  - attr(*, \"parameters\")=List of 2\n#>   ..$ a: num [1:92] 0.000123 0.000427 0.000296 0.000199 0.000187 ...\n#>   ..$ m: num [1:92] 0.01204 0.01307 0.01998 0.01067 0.00756 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# O resultado é um data.frame com:\n# - raw: taxas brutas (crude rates)\n# - est: estimativas suavizadas (local empirical Bayes)\n\n# Adicionar os resultados ao mapa\nmapa_rj <- mapa_rj |>\n    mutate(\n        taxa_bruta = eb_local$raw * 100000,           # taxa bruta por 100.000\n        taxa_suavizada_local = eb_local$est * 100000, # taxa suavizada local por 100.000\n        rr_suavizado_local = eb_local$est / (sum(casos)/sum(pop2022))  # risco relativo\n    )\n\n# ============================================================================\n# EXTRAIR OS PARÂMETROS LOCAIS (phi e gamma)\n# ============================================================================\n\n# Os parâmetros locais estão armazenados como atributo\nparametros_locais <- attr(eb_local, \"parameters\")\n\n# Adicionar ao mapa\nmapa_rj <- mapa_rj |>\n    mutate(\n        phi_local = parametros_locais$a,    # parâmetro phi (α local)\n        gamma_local = parametros_locais$m   # parâmetro gamma (β local)\n    )\n\n# ============================================================================\n# 5. COMPARAÇÃO: Bayes Empírico Global vs Local\n# ============================================================================\n\n# Se você já tem o Bayes Empírico global (ex: SpatialEpi::eBayes)\n# Vamos supor que já calculou eb_global anteriormente\n\n# Calcular Bayes Empírico global para comparação\nlibrary(SpatialEpi)\ntaxa_global <- sum(mapa_rj$casos) / sum(mapa_rj$pop2022)\nmapa_rj$casos_esperados <- mapa_rj$pop2022 * taxa_global\neb_global <- eBayes(Y = mapa_rj$casos, E = mapa_rj$casos_esperados)\n\nmapa_rj <- mapa_rj |>\n    mutate(\n        rr_bayes_global = eb_global$RR,\n        taxa_suavizada_global = rr_bayes_global * taxa_global * 100000\n    )\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# 6. MAPAS COMPARATIVOS\n# ============================================================================\n\n# Mapa 1: Taxa Bruta\np1 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = taxa_bruta), color = \"gray50\", size = 0.2) +\n    scale_fill_viridis_c(name = \"Casos/100.000\", direction = -1) +\n    labs(title = \"A) Taxa Bruta\") +\n    theme_minimal() +\n    theme(legend.position = \"bottom\")\n\n# Mapa 2: Bayes Empírico Global\np2 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = taxa_suavizada_global), color = \"gray50\", size = 0.2) +\n    scale_fill_viridis_c(name = \"Casos/100.000\", direction = -1) +\n    labs(title = \"B) Bayes Empírico Global\") +\n    theme_minimal() +\n    theme(legend.position = \"bottom\")\n\n# Mapa 3: Bayes Empírico Local (EBlocal)\np3 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = taxa_suavizada_local), color = \"gray50\", size = 0.2) +\n    scale_fill_viridis_c(name = \"Casos/100.000\", direction = -1) +\n    labs(title = \"C) Bayes Empírico Local (EBlocal)\") +\n    theme_minimal() +\n    theme(legend.position = \"bottom\")\n\n# Combinar\nlibrary(patchwork)\n(p1 + p2 + p3)\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# MAPAS COM GGPLOT2\n# ============================================================================\n\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(viridis)\n\n# Definir tema comum\ntheme_maps <- theme_minimal() +\n    theme(\n        plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5),\n        plot.subtitle = element_text(size = 10, hjust = 0.5),\n        legend.position = \"right\",\n        legend.title = element_text(size = 10, face = \"bold\"),\n        legend.text = element_text(size = 8),\n        panel.grid = element_blank(),\n        axis.text = element_blank(),\n        axis.title = element_blank(),\n        plot.margin = margin(10, 10, 10, 10)\n    )\n\n# Mapa 1: Incidência Bruta\np1 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = incidencia), color = \"gray50\", size = 0.2) +\n    scale_fill_viridis_c(\n        option = \"plasma\",\n        name = \"Casos/100.000 hab\",\n        labels = scales::comma,\n        direction = -1\n    ) +\n    labs(\n        title = \"A) Incidência Bruta\",\n        subtitle = \"Dengue no Rio de Janeiro - 2025\"\n    ) +\n    theme_maps\n\n# Mapa 2: Incidência Suavizada\np2 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = incidencia_suavizada), color = \"gray50\", size = 0.2) +\n    scale_fill_viridis_c(\n        option = \"plasma\",\n        name = \"Casos/100.000 hab\",\n        labels = scales::comma,\n        direction = -1\n    ) +\n    labs(\n        title = \"B) Incidência Suavizada\",\n        subtitle = \"Bayes Empírico - Posterior Mean\"\n    ) +\n    theme_maps\n\n# Combinar os 3 mapas\nmapas_combinados_ggplot <- (p1 + p2)\nmapas_combinados_ggplot\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Mapa 3: Risco Relativo Bayes\np3 <- ggplot(mapa_rj) +\n    geom_sf(aes(fill = rr_ebayes), color = \"gray50\", size = 0.2) +\n    scale_fill_gradient2(\n        low = \"blue\",\n        mid = \"white\",\n        high = \"red\",\n        midpoint = 1,\n        name = \"Risco Relativo\",\n        labels = scales::number,\n        limits = c(0, max(mapa_rj$rr_ebayes, na.rm = TRUE))\n    ) +\n    labs(\n        title = \"C) Risco Relativo Bayesiano\",\n        subtitle = \"Risco em relação à média estadual (RR = 1)\"\n    ) +\n    theme_maps\n\np3\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(mapa_rj$incidencia_suavizada, mapa_rj$incidencia)\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## **Aplicação III:** Utilizando o Estimador de Bayes Empírico  nos dados de Hanseniase no Mato Grosso\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ============================================================================\n# LER A PLANILHA\n# ============================================================================\nhansen <- read.csv2(\"dados/hansen/dados_hanseniase_mt.csv\") |>\n    mutate(\n        tx_detecao = casos / pop2022 * 100000\n    )\n\nhead(hansen)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"code_muni\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"name_muni\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"pop2022\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"casos\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"tx_detecao\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"5100102\",\"2\":\"Acorizal\",\"3\":\"5000\",\"4\":\"3\",\"5\":\"60.00000\",\"_rn_\":\"1\"},{\"1\":\"5100201\",\"2\":\"Água Boa\",\"3\":\"11000\",\"4\":\"80\",\"5\":\"727.27273\",\"_rn_\":\"2\"},{\"1\":\"5100250\",\"2\":\"Alta Floresta\",\"3\":\"24000\",\"4\":\"36\",\"5\":\"150.00000\",\"_rn_\":\"3\"},{\"1\":\"5100300\",\"2\":\"Alto Araguaia\",\"3\":\"7000\",\"4\":\"1\",\"5\":\"14.28571\",\"_rn_\":\"4\"},{\"1\":\"5100359\",\"2\":\"Alto Boa Vista\",\"3\":\"8000\",\"4\":\"6\",\"5\":\"75.00000\",\"_rn_\":\"5\"},{\"1\":\"5100409\",\"2\":\"Alto Garças\",\"3\":\"5000\",\"4\":\"3\",\"5\":\"60.00000\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### Lendo o Mapa via `geobr`\n\nPara acessar os dados dos limites territoriais de todos os estados brasileiros é necessário utilizar a função `read_state`.\n\n\n::: {.cell layout-align=\"center\" comments='null'}\n\n```{.r .cell-code}\nlibrary(geobr)\n\n# Baixar a malha municipal do estado do MAto Grosso\n# code_muni = 33 (código do estado do RJ)\n\nmapa_mt <- read_municipality(code_muni = 51, year = 2024) |>\n        mutate(code_muni = as.character(code_muni))\n```\n:::\n\n  \n## **Aplicação IV:** Utilizando dos modelos de regressão espaciais nos dados de queimadas no estado do Rio de Janeiro.\n\n####  Introdução aos Modelos de Regressão Espacial\n\nAlém das análises exploratórias para os dados espaciais de área, é possível avançar na modelagem estatística dos dados por meio de modelos espaciais que consideram a dependência espacial dos dados. Entre os mais utilizados estão os modelos de autocorrelação espacial global, como o **SAR (Simultaneous Autoregressive Model)** e o **CAR (Conditional Autoregressive Model)** (CRESSIE, 1993). O modelo SAR incorpora a dependência espacial diretamente no valor da variável dependente, assumindo que o valor observado em uma região é influenciado pelos valores das regiões vizinhas. Já o modelo CAR considera essa dependência na estrutura do erro, sendo muito utilizado em abordagens bayesianas para modelagem de risco em áreas geográficas.\n\nOutra abordagem é a dos modelos com efeitos espaciais locais, como a **Regressão Geograficamente Ponderada (GWR)** (FOTHERINGHAM et al., 2002). Diferente dos modelos SAR e CAR, que assumem relações espaciais globais, o GWR permite que os coeficientes da regressão variem ao longo do espaço, ajustando uma equação específica para cada localidade. Isso possibilita identificar como os efeitos de uma variável explicativa sobre a resposta mudam de acordo com a localização, sendo especialmente útil em contextos onde há forte heterogeneidade espacial. \n\n#### Na prática\n\n* <span style=\"color:orange; font-weight:bold;\"> Hipótese de independência das observações em geral é Falsa </span> $\\rightarrow$  Existe dependência espacial, ou seja, o valor observado em uma localização tende a se parecer com os valores observados em locais vizinhos.\n\n* Efeitos Espaciais $\\rightarrow$ Se existir dependência ou correlação espacial significativa, devemos incluir no modelo os <span style=\"color:darkpurple; font-weight:bold;\"> Efeitos Espaciais </span>, caso contrário, as estimativas geradas pelo modelo de regressão podem ficar enviesadas, criando associações espúrias (isto é, sugerindo relações estatísticas onde elas não existem de fato, ou mascarando relações reais);\n\n* <span style=\"color:darkred; font-weight:bold;\">**Como verificar ?** </span> $\\rightarrow$ Para detectar a dependência espacial, podemos analisar os resíduos da regressão tradicional (OLS), utilizando indicadores como o índice de Moran dos resíduos. Se os resíduos mostrarem autocorrelação espacial significativa, isso indica que há estrutura espacial não modelada.\n\n* <span style=\"color:darkblue; font-weight:bold;\">**Detectada a autocorrelação espacial: e agora ?** </span> $\\rightarrow$  É necessário adotar modelos de regressão que incorporem explicitamente os efeitos espaciais, evitando vieses nas estimativas dos coeficientes.\n\n\n#### i) Modelos Globais: \n\n* Esses modelos assumem que a estrutura espacial é constante em todo o espaço geográfico. Utilizam um único parâmetro para captar a autocorrelação.\n\n* Um exemplo é o **Modelo de Erro Espacial** (*Spatial Error Model* - **CAR**), representado por:\n  \n  $$y_i = \\beta_0 + \\sum^{p}_{k} \\beta_k x_{ik}  + \\varepsilon_i \\text{    , sendo  }  \\varepsilon_i = \\lambda  W + \\xi$$\n  \n::: box-dica4\nSendo:\n  \n- $y_i$: valor observado da variável dependente na unidade $i$;\n\n- $\\beta_0$: intercepto da regressão;\n\n- $\\beta_k$: coeficiente da $k$-ésima variável explicativa;\n\n- $x_{ik}$: valor da $k$-ésima variável explicativa para a unidade $i$;\n\n- $\\varepsilon_i$: erro com estrutura de autocorrelação espacial;\n\n\n- $\\lambda$: coeficiente de autocorrelação espacial;\n\n- $W$: matriz de vizinhança espacial (define como cada unidade está conectada às outras);\n\n- $\\xi$: erro aleatório normal (sem autocorrelação).\n:::\n  \n$\\rightarrow$ Podemos observar que os efeitos da autocorrelação espacial são associados ao termo de erro.\n\n::: box-dica2\n\n🧠 Interpretação:\n  \n  - Se $\\lambda \\ne 0$, há evidência de dependência espacial nos erros, ou seja, o erro em uma localidade está correlacionado com os erros em localidades vizinhas.\n\n- Se $\\lambda = 0$, o modelo reduz-se a uma regressão tradicional, e não há autocorrelação espacial significativa.\n:::\n  \n  \n  \n#### ii) Modelos Locais: \n  \n* Enquanto os modelos globais assumem uma relação espacial uniforme, os modelos locais admitem que os parâmetros da regressão variam ao longo do espaço geográfico.\n\n* Um exemplo clássico é o Modelo **Geograficamente Ponderado** (*Geographically Weighted Regression* - **GWR**), expresso por:\n  \n  \n\\[\n    y_i = \\beta_{0}(u_i, v_i) + \\sum_{k=1}^{p} \\beta_k(u_i, v_i) \\cdot x_{ik} + \\varepsilon_i,\n    \\\\\n    \\quad \\text{com } \\beta_k(u_i, v_i) \\text{ estimado via } \n    \\sum_{j=1}^{n} K(d_{ij}) \\cdot x_{jk}\n    \\]\n\n::: box-dica4\n\nOnde:\n  \n- $(u_i, v_i)$: coordenadas geográficas da observação $i$;\n\n- $\\beta_k(u_i, v_i)$: coeficiente local da variável explicativa $x_k$, estimado para a posição $i$;\n\n- $K(d_{ij})$: função kernel que atribui um peso à observação $j$ com base na distância $d_{ij}$ entre as localizações $i$ e $j$;\n:::\n  \n  \n**Efeito da vizinhança no GWR**: No GWR, para estimar os coeficientes de regressão em cada local, utiliza-se um \"kernel espacial\". O objetivo do kernel é dar mais peso para observações próximas e menos peso para as distantes. A forma e o alcance desse kernel são definidos por um parâmetro chamado largura de banda (*bandwidth*).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](figuras/largura_banda_gwr.png){fig-align='center' width=80%}\n:::\n:::\n\n\n$\\rightarrow$ Quanto menor $d_{ij}$, maior é o peso de $j$ na estimação de $\\beta_k(u_i, v_i)$.\n\n[Fonte: ARDILLY, Pascal et al. Manuel d’analyse spatiale. 2018.](https://ec.europa.eu/eurostat/documents/3859598/9462709/INSEE-ESTAT-SPATIAL-ANA-18-EN.pdf)\n\n\n#### Lendo os dados de queimadas no estado do Rio de Janeiro em 2025 \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# lendo a base de queimadas\ndados <- readxl::read_excel(\"dados/queimadas/queimadas_area.xlsx\")\n```\n:::\n\n\n#### Lendo o mapa do Rio de Janeiro e fazendo o merge com os dados de queimadas\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# lendo o mapa do Rio de Janeiro\nlibrary(sf)\n\n# Ler o arquivo\nmapa_rj <- st_read(\"malhas/mapa_rj.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Reading layer `mapa_rj' from data source \n#>   `/home/wagner/Downloads/spatial_ebook_quarto/spatial_ebook_project/malhas/mapa_rj.shp' \n#>   using driver `ESRI Shapefile'\n#> Simple feature collection with 92 features and 7 fields\n#> Geometry type: MULTIPOLYGON\n#> Dimension:     XY\n#> Bounding box:  xmin: -44.88932 ymin: -23.36893 xmax: -40.95794 ymax: -20.76321\n#> Geodetic CRS:  SIRGAS 2000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\n# Padronizar os nomes dos municípios em ambos os dataframes\nmapa_rj <- mapa_rj %>%\n  mutate(name_mn = tolower(name_mn))\n\ndados <- dados %>%\n  mutate(name_mn = tolower(name_mn))\n\n# Fazer o left join usando as novas colunas padronizadas\nmapa_rj <- mapa_rj %>%\n  left_join(dados, by = \"name_mn\")\n```\n:::\n\n\n#### Checando a variável resposta a presença de autocorrelação.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmapa_seq <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = media_frp), color = \"black\", size = 0.1) +\n  scale_fill_gradientn(\n    colors = c(\"#2c7bb6\", \"#abd9e9\", \"#ffffbf\", \"#fdae61\", \"#d7191c\"),\n    name = \"FRP Médio\"\n  ) +\n  labs(title = \"Média do FRP - Personalizado\") +\n  theme_void()\n\n\nmapa_seq\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n#### Moran Global do FRP Médio\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmoran.test(mapa_rj$media_frp, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  mapa_rj$media_frp  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = 2.466, p-value = 0.006831\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>       0.169628429      -0.010989011       0.005364412\n```\n\n\n:::\n:::\n\n\n#### Ajustando o modelo de regressão linear simples vazio\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqueimadas.lm <- lm(media_frp ~ 1, data = mapa_rj)\nsummary(queimadas.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = media_frp ~ 1, data = mapa_rj)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.0603 -0.7348  0.5683  1.6052  2.9134 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)   4.0603     0.2133   19.03   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.046 on 91 degrees of freedom\n```\n\n\n:::\n:::\n\n\n#### Colocando a variável `media_dias_sem_chuva` no modelo\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ajustando o modelo de regressão linear simples\nqueimadas.lm2 <- lm(media_frp ~ media_dias_sem_chuva, data = mapa_rj)\nsummary(queimadas.lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = media_frp ~ media_dias_sem_chuva, data = mapa_rj)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -3.0672 -1.2250  0.5633  1.1730  2.6210 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           3.05612    0.26174  11.676  < 2e-16 ***\n#> media_dias_sem_chuva  0.16462    0.03019   5.453 4.31e-07 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 1.784 on 90 degrees of freedom\n#> Multiple R-squared:  0.2483,\tAdjusted R-squared:   0.24 \n#> F-statistic: 29.73 on 1 and 90 DF,  p-value: 4.309e-07\n```\n\n\n:::\n:::\n\n\n#### Checando os residuos para verificar a presença de autocorrelação.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(spdep)\nqueimadas.lm$lmresid <- residuals(queimadas.lm)\nmoran.test(queimadas.lm$lmresid, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  queimadas.lm$lmresid  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = 2.466, p-value = 0.006831\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>       0.169628429      -0.010989011       0.005364412\n```\n\n\n:::\n:::\n\n\n#### Ajustando o modelo CAR (Spatial Error Model) vazio\n\nO **Modelo de Erro Espacial** (*Spatial Error Model* - **CAR**), representado por:\n    \n$$y_i = \\beta_0 + \\sum^{p}_{k} \\beta_k x_{ik}  + \\varepsilon_i$$\n$$\\varepsilon_i = \\lambda  W + \\xi$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(spatialreg)\nqueimadas.car <- errorsarlm(media_frp ~ 1, data = mapa_rj, listw = pesos.viz, Durbin = FALSE)\nsummary(queimadas.car)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:errorsarlm(formula = media_frp ~ 1, data = mapa_rj, listw = pesos.viz, \n#>     Durbin = FALSE)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -4.52836 -0.78012  0.63859  1.40498  3.02371 \n#> \n#> Type: error \n#> Coefficients: (asymptotic standard errors) \n#>             Estimate Std. Error z value  Pr(>|z|)\n#> (Intercept)  3.98226    0.28495  13.975 < 2.2e-16\n#> \n#> Lambda: 0.28059, LR test value: 4.5504, p-value: 0.032912\n#> Asymptotic standard error: 0.1285\n#>     z-value: 2.1836, p-value: 0.028992\n#> Wald statistic: 4.7681, p-value: 0.028992\n#> \n#> Log likelihood: -193.6419 for error model\n#> ML residual variance (sigma squared): 3.8661, (sigma: 1.9663)\n#> Number of observations: 92 \n#> Number of parameters estimated: 3 \n#> AIC: 393.28, (AIC for lm: 395.83)\n```\n\n\n:::\n:::\n\n\n::: box-dica1\n\n* O Intercepto: $3,982$ ($p < 0.001$), representa a média estimada de `media_frp` na ausência de preditores.\n\n* Lambda ($λ =  0,28059$) é o parâmetro de autocorrelação espacial dos erros. Quanto mais próximo de $0$ (zero) for o valor valor de lambda, pouca ou nenhuma autocorrelação espacial nos erros, ou seja, nesse caso podemos observar uma dependência espacial moderada.\n\n* Testes de Significância do Lambda\n\n| Teste | Estatística | p-valor | Interpretação |\n|-------|------------|---------|---------------|\n| **LR test** | 4.5504 | 0.0329 | O modelo espacial é superior ao OLS |\n| **z-value** | 2.1836 | 0.0290 | Lambda significativamente diferente de 0 |\n| **Wald** | 4.7681 | 0.0290 | Confirma a significância do parâmetro espacial |\n\n\n* A variância residual estimada é de $3,8661$.\n\n* O modelo espacial tem AIC menor que o modelo clássico (lm):\nAIC spatial $=$  $393,28$ $<$ AIC lm $=$ $395,83$, o que indica que o modelo com erro espacial se ajusta melhor aos dados.\n\n:::\n\n#### Colocando a variável `media_dias_sem_chuva` no modelo\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqueimadas.car2 <- errorsarlm(media_frp ~ media_dias_sem_chuva, data = mapa_rj, listw = pesos.viz, Durbin = FALSE)\nsummary(queimadas.car2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:errorsarlm(formula = media_frp ~ media_dias_sem_chuva, data = mapa_rj, \n#>     listw = pesos.viz, Durbin = FALSE)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -3.49610 -1.05656  0.45406  1.15077  2.47961 \n#> \n#> Type: error \n#> Coefficients: (asymptotic standard errors) \n#>                      Estimate Std. Error z value  Pr(>|z|)\n#> (Intercept)          3.027598   0.299065 10.1236 < 2.2e-16\n#> media_dias_sem_chuva 0.158451   0.029591  5.3548 8.566e-08\n#> \n#> Lambda: 0.24717, LR test value: 3.1804, p-value: 0.074528\n#> Asymptotic standard error: 0.13111\n#>     z-value: 1.8851, p-value: 0.059411\n#> Wald statistic: 3.5537, p-value: 0.059411\n#> \n#> Log likelihood: -181.1966 for error model\n#> ML residual variance (sigma squared): 2.9631, (sigma: 1.7214)\n#> Number of observations: 92 \n#> Number of parameters estimated: 4 \n#> AIC: 370.39, (AIC for lm: 371.57)\n```\n\n\n:::\n:::\n\n\n::: box-dica1\n\n* Media de Dias Sem Chuva: $0,1585$ ($p < 0,001$), representa a cada aumento de 1 dia na média sem chuva, a intensidade das queimadas (FRP) aumenta **0.1585 unidades**\n\n* Lambda ($λ =  0,24717$), fazendo uma comparação com modelo nulo ($\\lambda = 0.28059$), apresenta uma\nredução de $0,28059 \\rightarrow 0,24717$ $(\\downarrow 11.9\\%)$. Podemos dizer que a variável `media_dias_sem_chuva` explicou parte da dependência espacial.\n\n* Testes de Significância do Lambda\n\n| Teste | Estatística | p-valor | Interpretação |\n|-------|------------|---------|---------------|\n| **LR test** | 3.1804 | 0.0745 | Marginalmente não significativo |\n| **z-value** | 1.8851 | 0.0594 | Tendência à significância |\n| **Wald** | 3.5537 | 0.0594 | Confirma a tendência |\n\n* A variância residual estimada é de $2,96$.\n\n* O modelo espacial com a variável `media_dias_sem_chuva` tem AIC menor que o modelo espacial vazio:\nAIC spatial $=$  $370,39$ $<$ AIC vazio $=$ $393,28$, o que indica que o modelo com erro espacial com a variável `media_dias_sem_chuva` se ajusta melhor aos dados.\n\n:::\n\n#### Checando os residuos para verificar a presença de autocorrelação\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqueimadas.car2$carresid <- residuals(queimadas.car2)\nmoran.test(queimadas.car2$carresid, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  queimadas.car2$carresid  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = 0.082822, p-value = 0.467\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>      -0.004904690      -0.010989011       0.005396707\n```\n\n\n:::\n:::\n\n\nComo o $p-valor = 0,467 > 0,05$, não rejeitamos a hipótese nula de ausência de autocorrelação espacial nos resíduos. Isso indica que o modelo `errorsarlm` com a variável `media_dias_sem_chuva` eliminou adequadamente a autocorrelação espacial presente nos dados. \n\nEsse é exatamente o objetivo do modelo `errorsarlm`, capturar a estrutura espacial nos erros. E a ausência de autocorrelação nos resíduos valida a adequação desse modelo para os seus dados.\n\n#### Ajustando o modelo GWR (Geographically Weighted Regression)\n\n- Primeiro vamos extrair as coordenadas dos centróides dos municípios do estado do Rio de Janeiro\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Método 1: Converter para Spatial explicitamente\nmapa_rj_sp <- as(mapa_rj, \"Spatial\")\n\n# Calcular centróides\ncentroides <- coordinates(mapa_rj_sp)\ncolnames(centroides) <- c(\"X\", \"Y\")\ncentroides <- as.data.frame(centroides)\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Biblioteca para ajustar o modelos GWR\nlibrary(spgwr)\n\n# Estimando a largura de banda “ideal” para o kernel\nGWRbanda <- gwr.sel(media_frp ~ media_dias_sem_chuva, data = mapa_rj, coords = cbind(centroides$X, centroides$Y), adapt = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Adaptive q: 0.381966 CV score: 293.4932 \n#> Adaptive q: 0.618034 CV score: 296.7592 \n#> Adaptive q: 0.236068 CV score: 289.9323 \n#> Adaptive q: 0.145898 CV score: 288.4483 \n#> Adaptive q: 0.09016994 CV score: 285.4548 \n#> Adaptive q: 0.05572809 CV score: 285.7907 \n#> Adaptive q: 0.07987728 CV score: 282.4057 \n#> Adaptive q: 0.07333389 CV score: 281.0064 \n#> Adaptive q: 0.06660907 CV score: 282.5018 \n#> Adaptive q: 0.07337458 CV score: 280.9996 \n#> Adaptive q: 0.07477684 CV score: 280.7808 \n#> Adaptive q: 0.07672504 CV score: 280.9138 \n#> Adaptive q: 0.07524119 CV score: 280.7143 \n#> Adaptive q: 0.07551136 CV score: 280.677 \n#> Adaptive q: 0.07597495 CV score: 280.6152 \n#> Adaptive q: 0.07626146 CV score: 280.6866 \n#> Adaptive q: 0.07587383 CV score: 280.6284 \n#> Adaptive q: 0.07608438 CV score: 280.601 \n#> Adaptive q: 0.07615202 CV score: 280.6327 \n#> Adaptive q: 0.07604258 CV score: 280.6064 \n#> Adaptive q: 0.07608438 CV score: 280.601\n```\n\n\n:::\n:::\n\n\n::: box-dica2\n\n- Carregando o pacote `spgwr`, que é usado para rodar regressões ponderadas geograficamente (GWR). Essa técnica permite que os coeficientes variem no espaço, ou seja, ela mostra como o efeito de uma variável muda de lugar para lugar.\n\n- `gwr.sel()` é uma função que ajuda a escolher a largura de banda (bandwidth) \"ideal\" para o modelo GWR. A largura de banda controla o raio de influência espacial ao redor de cada ponto (quais vizinhos têm mais peso).\n\n  * Quanto menor a banda $rightarrow$ modelo mais local (mais sensível ao espaço).\n\n  * Quanto maior $rightarrow$ modelo mais global (menos sensível ao espaço).\n\n**OBS:** Esse valor de `q` representa a proporção de vizinhos usada para construir o kernel. Depois, ao ajustar o modelo com a função `gwr()`, será calculada internamente a distância física real correspondente em metros para cada ponto com base nas coordenadas UTM.  \n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ajustando o modelo GWR\nqueimadas.gwr = gwr(media_frp ~ media_dias_sem_chuva, data = mapa_rj, coords = cbind(centroides$X, centroides$Y), adapt = GWRbanda, hatmatrix = TRUE, se.fit = TRUE)\n\nqueimadas.gwr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> gwr(formula = media_frp ~ media_dias_sem_chuva, data = mapa_rj, \n#>     coords = cbind(centroides$X, centroides$Y), adapt = GWRbanda, \n#>     hatmatrix = TRUE, se.fit = TRUE)\n#> Kernel function: gwr.Gauss \n#> Adaptive quantile: 0.07608438 (about 6 of 92 data points)\n#> Summary of GWR coefficient estimates at data points:\n#>                         Min. 1st Qu.  Median 3rd Qu.    Max. Global\n#> X.Intercept.         1.47433 2.52055 2.98529 3.61925 4.57382 3.0561\n#> media_dias_sem_chuva 0.42156 0.54171 0.62107 0.73118 0.99266 0.1646\n#> Number of data points: 92 \n#> Effective number of parameters (residual: 2traceS - traceS'S): 19.59083 \n#> Effective degrees of freedom (residual: 2traceS - traceS'S): 72.40917 \n#> Sigma (residual: 2traceS - traceS'S): 1.65616 \n#> Effective number of parameters (model: traceS): 14.18723 \n#> Effective degrees of freedom (model: traceS): 77.81277 \n#> Sigma (model: traceS): 1.59762 \n#> Sigma (ML): 1.469282 \n#> AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 368.7429 \n#> AIC (GWR p. 96, eq. 4.22): 346.0703 \n#> Residual sum of squares: 198.6085 \n#> Quasi-global R2: 0.4788113\n```\n\n\n:::\n:::\n\n\n::: box-dica2\n\n- `coords = cbind(X, Y)`:\tCoordenadas dos pontos onde será ajustado o modelo (em nosso caso são os centroides dos setores).\n\n- `adapt = GWRbanda`:\tUsando a largura de banda adaptativa \"ideal\" já estimada (GWRbanda), que define o raio de influência espacial.\n\n- `hatmatrix = TRUE`:\tRetorna a matriz com estimativas usadas para cálculos como AIC e diagnóstico de resíduos.\n\n- `se.fit = TRUE`:\tCalcula os erros padrão das estimativas locais dos coeficientes.\n\n:::\n\n\nEsse modelo permite analisar como o efeito da variável `media_dias_sem_chuva` sobre `media_frp` muda de um município para outro no estado do Rio de Janeiro. Em vez de um único coeficiente como na regressão tradicional, o GWR estima um coeficiente diferente para cada município.\n\n::: box-dica1\n\n* `Kernel function: gwr.Gauss` → O modelo usou um kernel gaussiano, que atribui mais peso a vizinhos próximos.\n\n* `Adaptive quantile: 0,07608438` → Como `adapt = TRUE`, a largura de banda representa uma proporção dos pontos vizinhos.\n\n- Quanto aos coeficientes do modelo, cada linha refere-se à distribuição dos coeficientes locais estimados em cada ponto do espaço (284 no total). \n\n  * Por exemplo, o impacto da variável `media_dias_sem_chuva` sobre `media_frp` varia bastante no espaço, onde os municípios poder ter coeficientes de inclinação podem variar de $0,4216$ até $0.9927$.\n  \n  * A coluna `Global` mostra o coeficiente que seria obtido numa regressão tradicional (OLS).\n  \n- `Sigma (residual)`:\tDesvio padrão dos resíduos do modelo GWR.\n\n- `AIC (GWR)`: \tCritério de informação de Akaike (quanto menor, melhor). Útil para comparar com OLS.\n\n- `AICc (corrigido)`: Versão do AIC corrigida para modelos com muitos parâmetros.\n\n- `Residual sum of squares`: Soma dos quadrados dos resíduos (menor = melhor ajuste).\n\n- `Quasi-global R²`: Explica $~48%$ da variabilidade de `media_frp`. Excelente ajuste para dados espaciais.\n\n:::\n\n✅  Podemos observar  através do ajuste do modelo que:\n\n* O modelo GWR encontrou variações espaciais significativas na relação entre `media_dias_sem_chuva` e `media_frp`.\n\n* Os coeficientes de lixo mudam no espaço, variando de fortemente negativos a levemente positivos.\n\n* O Quasi-R² de $74\\%$ indica que o modelo explica bem os dados.\n\n* A redução do AIC em relação ao modelo OLS (que tinha $AIC ≈ 371,57$) reforça a adequação do GWR ($AIC ≈ 346,07$).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Colocando a saída do modelo dentro de um objeto dataframe.\nresults <- as.data.frame(queimadas.gwr$SDF)\nhead(results)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"sum.w\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"X.Intercept.\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"media_dias_sem_chuva\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"X.Intercept._se\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"media_dias_sem_chuva_se\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gwr.e\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pred\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pred.se\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"localR2\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"media_dias_sem_chuva_EDF\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"X.Intercept._se_EDF\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"media_dias_sem_chuva_se_EDF\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pred.se.1\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"coord.x\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"coord.y\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"13.758581\",\"2\":\"3.287562\",\"3\":\"0.6492016\",\"4\":\"0.5001023\",\"5\":\"0.04913609\",\"6\":\"-1.7614869\",\"7\":\"3.948061\",\"8\":\"0.3697285\",\"9\":\"0.5819790\",\"10\":\"0.6729894\",\"11\":\"0.5184269\",\"12\":\"0.05093651\",\"13\":\"0.3832760\",\"14\":\"-44.38552\",\"15\":\"-22.93640\",\"_rn_\":\"1\"},{\"1\":\"12.452940\",\"2\":\"2.687876\",\"3\":\"0.6118953\",\"4\":\"0.4977529\",\"5\":\"0.05350111\",\"6\":\"-2.6878758\",\"7\":\"2.687876\",\"8\":\"0.4977529\",\"9\":\"0.2703353\",\"10\":\"0.6343161\",\"11\":\"0.5159914\",\"12\":\"0.05546148\",\"13\":\"0.5159914\",\"14\":\"-42.13464\",\"15\":\"-21.65233\",\"_rn_\":\"2\"},{\"1\":\"9.909068\",\"2\":\"1.959549\",\"3\":\"0.8796292\",\"4\":\"0.5759912\",\"5\":\"0.07816773\",\"6\":\"1.2643183\",\"7\":\"4.615111\",\"8\":\"0.4851971\",\"9\":\"0.4850156\",\"10\":\"0.9118603\",\"11\":\"0.5970964\",\"12\":\"0.08103192\",\"13\":\"0.5029755\",\"14\":\"-42.29293\",\"15\":\"-22.75538\",\"_rn_\":\"3\"},{\"1\":\"12.817136\",\"2\":\"4.285029\",\"3\":\"0.5152286\",\"4\":\"0.4506435\",\"5\":\"0.05541159\",\"6\":\"0.3617287\",\"7\":\"5.831533\",\"8\":\"0.6179535\",\"9\":\"0.4246468\",\"10\":\"0.5341074\",\"11\":\"0.4671558\",\"12\":\"0.05744196\",\"13\":\"0.6405963\",\"14\":\"-43.12162\",\"15\":\"-22.23538\",\"_rn_\":\"4\"},{\"1\":\"8.918455\",\"2\":\"1.507305\",\"3\":\"0.9540725\",\"4\":\"0.5972007\",\"5\":\"0.08109931\",\"6\":\"-1.5073049\",\"7\":\"1.507305\",\"8\":\"0.5972007\",\"9\":\"0.5077593\",\"10\":\"0.9890313\",\"11\":\"0.6190832\",\"12\":\"0.08407092\",\"13\":\"0.6190832\",\"14\":\"-41.95045\",\"15\":\"-22.77645\",\"_rn_\":\"5\"},{\"1\":\"12.601581\",\"2\":\"1.833271\",\"3\":\"0.8711638\",\"4\":\"0.4795234\",\"5\":\"0.06702291\",\"6\":\"-1.6893889\",\"7\":\"5.401345\",\"8\":\"0.5933233\",\"9\":\"0.4973426\",\"10\":\"0.9030847\",\"11\":\"0.4970940\",\"12\":\"0.06947874\",\"13\":\"0.6150636\",\"14\":\"-42.16848\",\"15\":\"-22.92170\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### Verificando a distribuição dos coeficientes de regressão para a variável `media_dias_sem_chuva`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(results$media_dias_sem_chuva)\nabline(v = median(results$media_dias_sem_chuva), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n#### Verificando a distribuição dos *localR2*\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(results$localR2)\nabline(v = median(results$localR2), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-53-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n#### Incorporando alguns parâmetros de saída do modelo na tabela *setor.sf*\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmapa_rj$coef_dias_sem_chuva <- results$media_dias_sem_chuva\nmapa_rj$localR2 <- results$localR2\nmapa_rj$pred.gwr <- results$pred\n```\n:::\n\n\n#### Mapa dos coeficientes de regressão para a variável lixo\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmap.dias_sem_chuvas <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = coef_dias_sem_chuva), color = \"black\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",      # para coeficientes negativos\n    mid = \"white\",     # para valores próximos de zero\n    high = \"darkred\",      # para coeficientes positivos\n    midpoint = 0,      # centraliza a escala no zero\n    name = \"Coef. dias sem chuva\"\n  ) +\n  ggtitle(\"Coef locais da variável dias sem chuva\") +\n  theme_void()\n\nmap.dias_sem_chuvas\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-55-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n#### Checando os residuos para verificar a presença de autocorrelação para o modelo GWR.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculando os resíduos para o modelo GWR\nresults$residuos <- mapa_rj$media_frp - results$pred\n\nmoran.test(results$residuos, pesos.viz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tMoran I test under randomisation\n#> \n#> data:  results$residuos  \n#> weights: pesos.viz    \n#> \n#> Moran I statistic standard deviate = 0.16606, p-value = 0.4341\n#> alternative hypothesis: greater\n#> sample estimates:\n#> Moran I statistic       Expectation          Variance \n#>       0.001212100      -0.010989011       0.005398377\n```\n\n\n:::\n:::\n\n\n#### Mapeando os coeficientes de regressão para a variável `media_dias_sem_chuva` por significancia através do teste de wald\n\nO teste de Wald é utilizado para avaliar a significância estatística dos coeficientes estimados em modelos de regressão, como a Regressão Ponderada Geograficamente (GWR). A estatística de Wald testa se o coeficiente estimado (\\(\\hat{\\beta}\\)) é significativamente diferente de zero, com base no seu erro padrão (\\(SE(\\hat{\\beta})\\)).\n\nA fórmula geral do teste é:\n\n\\[\nW = \\frac{|\\hat{\\beta}|}{SE(\\hat{\\beta})}\n\\]\n\nValores altos da estatística de Wald indicam maior evidência de que o coeficiente é significativamente diferente de zero. Sob a hipótese nula (\\(H_0: \\beta = 0\\)), a estatística de Wald segue uma distribuição normal padrão.\n\nNo contexto do modelo GWR, o teste de Wald foi aplicado ponto a ponto para o coeficiente local da variável `media_dias_sem_chuva`, utilizando a razão entre o valor absoluto do coeficiente estimado e seu erro padrão.\n\nPara fins de mapeamento, a estatística foi dicotomizada da seguinte forma:\n\n\\[\n\\texttt{wald.teste} =\n\\begin{cases}\n1 & \\text{se } W \\geq 2 \\ (\\text{coeficiente significativo}) \\\\\n0 & \\text{se } W < 2 \\ (\\text{coeficiente não significativo})\n\\end{cases}\n\\]\n\nO limiar de $2$ foi escolhido por ser uma aproximação prática do ponto de corte para um nível de significância de 5\\% (como \\(z = 1.96\\) na distribuição normal padrão).\n\nEssa abordagem permite visualizar espacialmente onde a variável `media_dias_sem_chuva` exerce um efeito estatisticamente significativo sobre a variável dependente `media_frp`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculando a estatística de wald\nmapa_rj$wald.teste <- abs(results$media_dias_sem_chuva/results$media_dias_sem_chuva_se)\n\n# Dicotomizando a estatística de wald\nmapa_rj$wald.teste_cat <- factor(ifelse(mapa_rj$wald.teste < 2, 0, 1),\n                                  levels = c(0, 1))\n\n\nmap.wald <- ggplot(mapa_rj) + \n            geom_sf(aes(fill = wald.teste_cat), color = \"black\") + \n            scale_fill_manual(values = c(\"white\", \"purple\"), \n                              labels = c(\"< 2\", \">= 2\"), \n                              name = \"Wald\",\n                              drop = FALSE) +  # Não dropar níveis\n            ggtitle(\"Teste Wald\") + \n            theme_void()\n\n\nlibrary(gridExtra)\ngrid.arrange(map.dias_sem_chuvas, map.wald, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-57-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n#### Mapa dos coeficientes de determinação regionalizados ($R^2$ local).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mapa_rj) +\n  geom_sf(aes(fill = localR2), color = \"black\", size = 0.1) +\n  scale_fill_viridis_c(option = \"viridis\",, direction = -1, name = expression(R^2~local)) +\n  ggtitle(\"Mapa dos coeficientes de determinação regionalizados (R² local)\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-58-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n#### Verificando a distribuição dos preditos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhistdens <- function(x, titulo = \"\") {\n  densi <- density(x)\n  xli <- range(densi$x)\n  yli <- range(densi$y)\n  hist(x, col = \"orange\", probability = T, xlim = xli, ylim = yli, main = titulo)\n  lines(densi, lwd = 2)\n  abline(v = median(x), lwd = 2, col = \"blue\", lty = 2)\n}\n\npar(mfrow = c(2, 2))\n\nhist.frp <- histdens(mapa_rj$media_frp, \"FRP médio\")\nhist.lm <- histdens(queimadas.lm2$fitted.values, \"Pred LM\")\nhist.car <- histdens(queimadas.car2$fitted.values, \"Pred CAR\")\nhist.gwr <- histdens(results$pred, \"Pred GWR\")\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-59-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n| Modelo       | Adesão à distribuição real       | Interpretação                                                                 |\n|--------------|----------------------------------|-------------------------------------------------------------------------------|\n| **FRP médio** | —                                | Distribuição observada com assimetria à direita e dispersão moderada, apresentando valores mais concentrados entre ~4 e 6, com presença de cauda. Serve como referência para avaliar os modelos.                         |\n| **Pred LM**  | ❌ Fraca                         | MDistribuição excessivamente concentrada em valores baixos, com perda de variabilidade e deslocamento da média em relação aos dados observados. O modelo linear não captura adequadamente a forma da distribuição.    |\n| **Pred CAR** | ✅ Razoável                      | CReproduz parcialmente a variabilidade e a amplitude dos valores, aproximando-se da distribuição observada, porém ainda apresenta suavização e leve deslocamento da média, reduzindo a assimetria.                     |\n| **Pred GWR** | ✅✅ Melhor                      | PrDistribuição mais próxima da observada, preservando melhor a dispersão, a posição da média e parte da assimetria, sugerindo maior capacidade do modelo em representar a heterogeneidade espacial dos dados.|\n\n\nApesar dos modelos analisarem apenas o efeito da variável `media_dias_sem_chuva` sobre a `media_frp`, observa-se que o modelo `GWR` foi o único capaz de gerar uma distribuição de preditos que preserva, em boa parte, a forma assimétrica e a dispersão da variável observada. Isso indica que o impacto de  `media_frp` não é homogêneo e varia conforme a localização. Modelos tradicionais como o `LM`, ao assumirem um coeficiente global, subestimam a variabilidade local, enquanto modelos espaciais (CAR) ou locais (GWR) conseguem representar melhor essa relação dependente do espaço.\n\n\n#### Mapeando os valores observados e preditos dos modelos ajustados\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\n\n# Define faixas de classes abrangentes\nbreaks_classes <- c(-Inf, 0, 2, 4, 10, Inf)\nlabels_classes <- c(\"< 0\", \"0 - 2\", \"2 - 4\", \"4 - 10\", \"> 10\")\n\n# -----------------------------------------\n# Taxa Bruta Observada\nmapa_rj$brks <- cut(mapa_rj$media_frp,\n                     breaks = breaks_classes,\n                     include.lowest = TRUE,\n                     right = TRUE,\n                     labels = labels_classes)\n\ntx.bruta <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks), color = \"black\", size = 0.1) +\n  scale_fill_brewer(palette = \"YlOrRd\", name = \"Taxa\") +\n  ggtitle(\"Taxa Bruta\") +\n  theme_void()\n\n# -----------------------------------------\n# Predito - LM\nmapa_rj$brks.lm <- cut(queimadas.lm2$fitted.values,\n                        breaks = breaks_classes,\n                        include.lowest = TRUE,\n                        right = TRUE,\n                        labels = labels_classes)\n\npred.lm <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.lm), color = \"black\", size = 0.1) +\n  scale_fill_brewer(palette = \"YlOrRd\", name = \"Taxa\") +\n  ggtitle(\"Taxa Predita - LM\") +\n  theme_void()\n\n# -----------------------------------------\n# Predito - CAR\nmapa_rj$brks.car <- cut(queimadas.car2$fitted.values,\n                         breaks = breaks_classes,\n                         include.lowest = TRUE,\n                         right = TRUE,\n                         labels = labels_classes)\n\npred.car <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.car), color = \"black\", size = 0.1) +\n  scale_fill_brewer(palette = \"YlOrRd\", name = \"Taxa\") +\n  ggtitle(\"Taxa Predita - CAR\") +\n  theme_void()\n\n# -----------------------------------------\n# Predito - GWR\nmapa_rj$brks.gwr <- cut(results$pred,\n                         breaks = breaks_classes,\n                         include.lowest = TRUE,\n                         right = TRUE,\n                         labels = labels_classes)\n\npred.gwr <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.gwr), color = \"black\", size = 0.1) +\n  scale_fill_brewer(palette = \"YlOrRd\", name = \"Taxa\") +\n  ggtitle(\"Taxa Predita - GWR\") +\n  theme_void()\n\n# -----------------------------------------\n# Mostrar mapas lado a lado\ngrid.arrange(tx.bruta, pred.lm, pred.car, pred.gwr, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-60-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n#### Comparando a distribuição dos resíduos dos modelos ajustados\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(vioplot)\n\n# Define os resíduos\nres_lm  <- queimadas.lm2$residuals\nres_car <- queimadas.car2$residuals\nres_gwr <- results$residuos\n\n# Paleta de cores agradável\ncores <- c(\"#66C2A5\", \"#FC8D62\", \"#8DA0CB\")  # Paleta Set2 do RColorBrewer\n\n# Gráfico violin com visual melhorado\nvioplot(\n  res_lm, res_car, res_gwr,\n  names = c(\"LM\", \"CAR\", \"GWR\"),\n  col = cores,\n  border = \"black\",\n  drawRect = TRUE     # mediana dos resíduos\n)\n\n# Título e rótulo do eixo Y\ntitle(main = \"Distribuição dos Resíduos por Modelo\", cex.main = 1.2)\nmtext(\"Resíduos\", side = 2, line = 2.5, cex = 1.1)\n\n# Linha horizontal em y = 0 para referência\nabline(h = 0, lty = 2, col = \"grey40\")\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-61-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n| Modelo | Centralidade dos resíduos | Dispersão | Presença de extremos | Interpretação |\n|------|---------------------------|-----------|---------------------|--------------|\n| **LM** | Aproximadamente centrados em zero | Moderada a alta | Moderada | Indica ausência de viés sistemático, porém com maior variabilidade dos erros. |\n| **CAR** | Próximos de zero | Moderada | Maior presença nas caudas | Sugere melhor acomodação da dependência espacial, mas ainda com ocorrência de resíduos extremos. |\n| **GWR** | Centrado em zero | Moderada | Menor concentração de extremos | Distribuição mais equilibrada dos resíduos, indicando melhor ajuste local e captura da heterogeneidade espacial. |\n\n\n#### Mapeando os resíduos dos modelos ajustados\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(colorspace)\nlibrary(gridExtra)\n\n# Quebras e rótulos\nbreaks_res <- c(-5, -2, -1, 1, 2, 5)\nlabels_res <- c(\"-5 a -2\", \"-2 a -1\", \"-1 a 1\", \"1 a 2\", \"2 a 5\")\n\n# ------------------------------\n# Resíduos - LM\nmapa_rj$brks.res.lm <- cut(queimadas.lm2$residuals,\n                            breaks = breaks_res,\n                            labels = labels_res,\n                            include.lowest = TRUE,\n                            right = TRUE)\n\nres.lm <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.res.lm), color = \"black\", size = 0.1) +\n  scale_fill_discrete_sequential(\n    palette = \"Purple-Yellow\",\n    name = \"Resíduo\",\n    na.value = \"grey75\",\n    drop = FALSE\n  ) +\n  guides(fill = guide_legend(reverse = TRUE)) +  # INVERTE A LEGENDA\n  ggtitle(\"Resíduos - LM\") +\n  theme_void()\n\n# ------------------------------\n# Resíduos - CAR\nmapa_rj$brks.res.car <- cut(queimadas.car2$residuals,\n                             breaks = breaks_res,\n                             labels = labels_res,\n                             include.lowest = TRUE,\n                             right = TRUE)\n\nres.car <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.res.car), color = \"black\", size = 0.1) +\n  scale_fill_discrete_sequential(\n    palette = \"Purple-Yellow\",\n    name = \"Resíduo\",\n    na.value = \"grey75\",\n    drop = FALSE\n  ) +\n  guides(fill = guide_legend(reverse = TRUE)) +  # INVERTE A LEGENDA\n  ggtitle(\"Resíduos - CAR\") +\n  theme_void()\n\n# ------------------------------\n# Resíduos - GWR\nmapa_rj$brks.res.gwr <- cut(results$residuos,\n                             breaks = breaks_res,\n                             labels = labels_res,\n                             include.lowest = TRUE,\n                             right = TRUE)\n\nres.gwr <- ggplot(mapa_rj) +\n  geom_sf(aes(fill = brks.res.gwr), color = \"black\", size = 0.1) +\n  scale_fill_discrete_sequential(\n    palette = \"Purple-Yellow\",\n    name = \"Resíduo\",\n    na.value = \"grey75\",\n    drop = FALSE\n  ) +\n  guides(fill = guide_legend(reverse = TRUE)) +  # INVERTE A LEGENDA\n  ggtitle(\"Resíduos - GWR\") +\n  theme_void()\n\n# ------------------------------\n# Exibir mapas\ngrid.arrange(res.lm, res.car, res.gwr, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](03-dados_area_files/figure-html/unnamed-chunk-62-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}