# Referências Bibliográficas

A seguir, apresentamos uma seleção de referências fundamentais para o aprofundamento nos temas abordados neste curso.

- **Bailey, T.C.; Gatrell, A.C.** *Interactive Spatial Data Analysis*. Routledge, 1995.

- **Bivand, R.S.; Pebesma, E.; Gomez-Rubio, V.** *Applied Spatial Data Analysis with R*. Springer, 2ª ed., 2013.

- **Brown, Evan.** The Variogram Basics: A visual introduction to one of the most useful geostatistical concepts. CSEG Recorder, v. 47, n. 1, jan. 2022. [Disponível aqui](https://csegrecorder.com/articles/view/the-variogram-basics-a-visual-intro-to-useful-geostatistical-concepts). Acesso em: 8 jun. 2026.

- **Cressie, N.** Statistics for Spatial Data. New York: Wiley, 1993.

- **Comber, L.** [GeoComputation and Spatial Analysis practicals](https://bookdown.org/lexcomber/GEOG3195/).

- **Druck, S.; Carvalho, M.S.; Câmara, G.; Monteiro, A.V.M.** (eds). [Análise Espacial de Dados Geográficos](http://www.dpi.inpe.br/gilberto/livro/analise/). Brasília: EMBRAPA, 2004.

- **Fotheringham, A. S.; Brunsdon, C.; Charlton, M. E.** *Geographically Weighted Regression: The Analysis of Spatially Varying Relationships*, 2002.

- **Hijmans, R.J.** [Spatial Data Science with R](https://rspatial.org/raster/index.html).

- **Isaaks, E. H.; Srivastava, R. M.** An Introduction to Applied Geostatistics.
New York: Oxford University Press, 1989.

- **Lovelace, R.; Nowosad, J.; Muenchow, J.** [Geocomputation with R](https://geocompr.robinlovelace.net/), 2021.

- **Lima, F. B.** Laboratório 5 – Geoestatística Linear. São José dos Campos: Instituto Nacional de Pesquisas Espaciais (INPE), 2007. Disponível em: [Wiki DPI/INPE – Laboratório 5 – Geoestatística Linear. Acesso em: 8 jun. 2026](https://wiki.dpi.inpe.br/lib/exe/fetch.php?media=1_lab5.pdf).

- **Moraga, P.** Spatial Data Science with R. [Disponível aqui.](https://www.paulamoraga.com/book-spatial/index.html)

- **Peterson, E.** [Spatial Epidemiology Workshop](https://bookdown.org/epeterson_2010/spatial_epidemiology_workshop), 2010.

- **Solymosi, R.; Medina, J.** [Crime Mapping in R](https://maczokni.github.io/crime_mapping_textbook/). University of Manchester.

- **Waller, L.A.; Gotway, C.A.** *Applied Spatial Statistics for Public Health Data*. Wiley-Interscience, 2004.

- **Webster, R.; Oliver, M. A.** Geostatistics for Environmental Scientists. 2. ed. Chichester: John Wiley & Sons, 2007.

